global:
  imagePullSecrets:
    - name: ghcr-creds

frontend:
  image:
    repository: ghcr.io/pushpendra2601/cloudcart-frontend
    tag: "39-873b774"
    pullPolicy: IfNotPresent

backend:
  image:
    repository: ghcr.io/pushpendra2601/cloudcart-backend
    tag: "39-873b774"
    pullPolicy: IfNotPresent