apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcart-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudcart.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  API_PORT: {{ .Values.backend.env.API_PORT | quote }}
  REDIS_HOST: {{ .Values.backend.env.REDIS_HOST | quote }}
  POSTGRES_HOST: {{ .Values.backend.env.POSTGRES_HOST | quote }}
