{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcart-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudcart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cloudcart-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudcart-frontend
                port:
                  name: http
{{- end }}
