apiVersion: v1
kind: Service
metadata:
  name: cloudcart-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cloudcart-redis
    {{- include "cloudcart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cloudcart-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
