apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudcart-readonly
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudcart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
