apiVersion: v1
kind: Secret
metadata:
  name: cloudcart-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudcart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
