apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudcart-app
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudcart.labels" . | nindent 4 }}
automountServiceAccountToken: false
